export const CONTEXT_DOMAINS_AND_SITES_ADD = 'CONTEXT_DOMAINS_AND_SITES_ADD';
export const CONTEXT_CHANGE_GMP_CONTEXT = 'CONTEXT_CHANGE_GMP_CONTEXT';
export const CONTEXT_CHANGE_SITE_IDS = 'CONTEXT_CHANGE_SITE_IDS';
export const CONTEXT_CHANGE_ALL = 'CONTEXT_CHANGE_ALL';

export const MANAGE_USER_ROLES_SET_ROLE_MAPPING = 'MANAGE_USER_ROLES_SET_ROLE_MAPPING';
export const MANAGE_USER_ROLES_SET_MANAGER_ROLES = 'MANAGE_USER_ROLES_SET_MANAGER_ROLES';
export const MANAGE_USER_ROLES_SET_MANAGER_PLACES = 'MANAGE_USER_ROLES_SET_MANAGER_PLACES';
export const MANAGE_USER_ROLES_SET_SEARCH_RESULTS = 'MANAGE_USER_ROLES_SET_SEARCH_RESULTS';
export const MANAGE_USER_ROLES_SELECT_USER = 'MANAGE_USER_ROLES_SELECT_USER';
export const MANAGE_USER_ROLES_CHECK_ROLE_FOR_DELETE = 'MANAGE_USER_ROLES_CHECK_ROLE_FOR_DELETE';
export const MANAGE_USER_ROLES_DELETE_ROLE = 'MANAGE_USER_ROLES_DELETE_ROLES';
export const MANAGE_USER_ROLES_SET_ASSIGNMENT_LOCATION =
    'MANAGE_USER_ROLES_SET_ASSIGNMENT_LOCATION';
export const MANAGE_USER_ROLES_CHECK_ROLE_FOR_ASSIGN = 'MANAGE_USER_ROLES_CHECK_ROLE_FOR_ASSIGN';
export const MANAGE_USER_ROLES_ASSIGN_ROLE = 'MANAGE_USER_ROLES_ASSIGN_ROLE';
export const MANAGE_USER_ROLES_ALL_ASSIGNED = 'MANAGE_USER_ROLES_ALL_ASSIGNED';
export const MANAGE_USER_ROLES_RESET = 'MANAGE_USER_ROLES_RESET';
export const MANAGE_USER_ROLES_INVALID_TOKEN = 'MANAGE_USER_ROLES_INVALID_TOKEN';
