// Manage Roles 
export const MANAGE_ROLES_SET_OBJECT = 'MANAGE_ROLES_SET_OBJECT';
export const MANAGE_ROLES_CHECK_ROLE_FOR_DELETE = 'MANAGE_ROLES_CHECK_ROLE_FOR_DELETE';
export const MANAGE_ROLES_DELETE_ROLE = 'MANAGE_ROLES_DELETE_ROLES';
export const MANAGE_ROLES_SET_ASSIGNMENT_LOCATION =
    'MANAGE_ROLES_SET_ASSIGNMENT_LOCATION';
export const MANAGE_ROLES_CHECK_ROLE_FOR_ASSIGN = 'MANAGE_ROLES_CHECK_ROLE_FOR_ASSIGN';
export const MANAGE_ROLES_ASSIGN_ROLE = 'MANAGE_ROLES_ASSIGN_ROLE';
export const MANAGE_ROLES_ASSIGNING = 'MANAGE_ROLES_ASSIGNING';
export const MANAGE_ROLES_ALL_ASSIGNED = 'MANAGE_ROLES_ALL_ASSIGNED';
export const MANAGE_ROLES_RESET = 'MANAGE_ROLES_RESET';
export const MANAGE_ROLES_SETUP = 'MANAGE_ROLES_SETUP';
export const MANAGE_ROLES_INVALID_TOKEN = 'MANAGE_ROLES_INVALID_TOKEN';

// User Settings
export const USER_SETTINGS_LOAD = 'USER_SETTINGS_LOAD';
export const USER_SETTINGS_HIDDEN_FIELDS_UPDATE = 'USER_SETTINGS_HIDDEN_FIELDS_UPDATE';