// Manage Invitation Roles
export const MANAGE_INVITATION_ROLES_SET_INVITATION = 'MANAGE_INVITATION_ROLES_SET_INVITATION';
export const MANAGE_INVITATION_ROLES_CHECK_ROLE_FOR_DELETE =
    'MANAGE_INVITATION_ROLES_CHECK_ROLE_FOR_DELETE';
export const MANAGE_INVITATION_ROLES_DELETE_ROLE = 'MANAGE_INVITATION_ROLES_DELETE_ROLE';
export const MANAGE_INVITATION_ROLES_SET_ASSIGNMENT_LOCATION =
    'MANAGE_INVITATION_ROLES_SET_ASSIGNMENT_LOCATION';
export const MANAGE_INVITATION_ROLES_CHECK_ROLE_FOR_ASSIGN =
    'MANAGE_INVITATION_ROLES_CHECK_ROLE_FOR_ASSIGN';
export const MANAGE_INVITATION_ROLES_ASSIGNING = 'MANAGE_INVITATION_ROLES_ASSIGNING';
export const MANAGE_INVITATION_ROLES_ALL_ASSIGNED = 'MANAGE_INVITATION_ROLES_ALL_ASSIGNED';
export const MANAGE_INVITATION_ROLES_ASSIGN_ROLE = 'MANAGE_INVITATION_ROLES_ASSIGN_ROLE';
export const MANAGE_INVITATION_ROLES_RESET = 'MANAGE_INVITATION_ROLES_RESET';

// Manage User Roles
export const MANAGE_USER_ROLES_SET_USER = 'MANAGE_USER_ROLES_SET_USER';
export const MANAGE_USER_ROLES_CHECK_ROLE_FOR_DELETE = 'MANAGE_USER_ROLES_CHECK_ROLE_FOR_DELETE';
export const MANAGE_USER_ROLES_DELETE_ROLE = 'MANAGE_USER_ROLES_DELETE_ROLES';
export const MANAGE_USER_ROLES_SET_ASSIGNMENT_LOCATION =
    'MANAGE_USER_ROLES_SET_ASSIGNMENT_LOCATION';
export const MANAGE_USER_ROLES_CHECK_ROLE_FOR_ASSIGN = 'MANAGE_USER_ROLES_CHECK_ROLE_FOR_ASSIGN';
export const MANAGE_USER_ROLES_ASSIGN_ROLE = 'MANAGE_USER_ROLES_ASSIGN_ROLE';
export const MANAGE_USER_ROLES_ASSIGNING = 'MANAGE_USER_ROLES_ASSIGNING';
export const MANAGE_USER_ROLES_ALL_ASSIGNED = 'MANAGE_USER_ROLES_ALL_ASSIGNED';
export const MANAGE_USER_ROLES_RESET = 'MANAGE_USER_ROLES_RESET';

// Shared Resources
export const SHARED_RESOURCES_SETUP = 'SHARED_RESOURCES_SETUP';
export const SHARED_RESOURCES_INVALID_TOKEN = 'SHARED_RESOURCES_INVALID_TOKEN';
