export const MANAGE_USER_ROLES_SET_SEARCH_RESULTS = 'MANAGE_USER_ROLES_SET_SEARCH_RESULTS';
export const MANAGE_USER_ROLES_SELECT_USER = 'MANAGE_USER_ROLES_SELECT_USER';
export const MANAGE_USER_ROLES_RESET = ' MANAGE_USER_ROLES_RESET';